DEFINE VARIABLE iNumero AS INTEGER     NO-UNDO.
DEFINE VARIABLE cString AS CHARACTER   NO-UNDO.

REPEAT WHILE LENGTH(cString) LE 200:
   iNumero = iNumero + 1.
   cString = SUBSTITUTE ("&1&2", cString, iNumero).
END.
MESSAGE cString SKIP
SUBSTRING(cString, 200, 1)
   VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.
